services:
  waterseg:
    build: .

    platform: linux/amd64 # mine is ARM but targetted is amd64
    image: waterbody-segmentation:latest
    volumes:
      - ./data:/data

    command: ["--input", "/data/input.tif", "--output", "/data/output.tif"] #passed at Dockerfile's entrypoint
